### ISSUE TITLE
Update to support rapidfuzz >=3

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/cleo-feedstock#16]
### Comment:

Hello !
https://github.com/python-poetry/cleo/issues/353
https://github.com/python-poetry/cleo/issues/353#issuecomment-1685305699

The feedstock pin on 
- rapidfuzz >=2.2.0,<3.0.0
Is preventing install of poetry with packages such as grayskull that require rapdifuzz>=3.0

Can the existing pin be changed to - rapidfuzz >=2.2.0,<3.0.0 to resolve this or do we need a new release first. 
Thank you & Regards.

**Comment by xylar** [comment]
Expanding on my comment on the upstream repo (https://github.com/python-poetry/cleo/issues/353#issuecomment-1685313262):

The `main` branch on the main cleo repo has already made this change.  
https://github.com/python-poetry/cleo/blob/main/pyproject.toml#L39
However, the pin for the latest release was what we use here:
https://github.com/python-poetry/cleo/blob/2.0.1/pyproject.toml#L36
We cannot use the source from `main` so they will need to make a new release before the updated pins on `rapidfuzz` can be used on conda-forge.

**Comment by rxm7706** [comment]
Addressed on https://github.com/python-poetry/cleo/issues/353
Feedstock is correct to the released version, and when cleo releases a new version, it will be addressed.

**Comment by xylar** [comment]
@rxm7706, this should be available shortly via #17
