### ISSUE TITLE
Yanked version of Cleo still on conda

### ISSUE THREAD

**Issue by emirkmo** [conda-forge/cleo-feedstock#20]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

https://github.com/python-poetry/poetry/issues/9856

The two most recent versions of cleo have been yanked due to API breakages. https://pypi.org/project/cleo/#history We should point back to the last working version 2.1.0 

### Installed packages

```shell
Irrelevant.
```

### Environment info

```shell
Irrelevant.
```

**Comment by xylar** [comment]
Marking that package (2.2.1) as broken here:
https://github.com/conda-forge/admin-requests/pull/1240

**Comment by xylar** [comment]
The PR has been merged and the package has the `broken` tag but it still has the `main` tag as well:
https://anaconda.org/conda-forge/cleo/files
I'll close this only when I can verify that it's actually not installable.

**Comment by xylar** [comment]
Okay, great:
```
$ conda create -y -n test cleo=2.2.1
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cleo=2.2.1

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
This is what we want.

**Comment by emirkmo** [comment]
Thanks for verifying!
